crds:
  # This option decides if the CRDs should be installed
  # as part of the Helm installation.
  enabled: true

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true


# dns01RecursiveNameservers fixed an issue with the propagation checks taking forever
# Theory: cert-manager was using the local DNS server running on my opnsense router
# /etc/resolv.conf refers to the local DNS server running on my opnsense router
dns01RecursiveNameservers: "1.1.1.1:53, 8.8.8.8:53"  

# Forces cert-manager to use only the recursive nameservers for verification.
# Enabling this option could cause the DNS01 self check to take longer owing to caching performed by the recursive nameservers.
dns01RecursiveNameserversOnly: false