apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.5.55
  share: /nfs-exports/kube
reclaimPolicy: Retain
volumeBindingMode: Immediate