apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.55.5
  share: /nfs-exports/default
reclaimPolicy: Retain
volumeBindingMode: Immediate