githubConfigUrl: "https://github.com/leonpjvaughan-org"

githubConfigSecret: "github-actions-secret"

runnerGroup: "KubernetesARC"  # created in https://github.com/organizations/<org>/settings/actions/runner-groups

template:
  spec:
    containers:      
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
        - name: ACTIONS_RUNNER_CONTAINER_HOOKS
          value: /home/runner/k8s/index.js  # built into the image
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "true"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "local-path"
              resources:
                requests:
                  storage: 1Gi


