
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rancher-httproute  # Replace with your desired name
  namespace: cattle-system
spec:
  parentRefs:
    - name: mydomain-istio-gw  # Replace with your gateway name
      namespace: default  # dont forget this
      sectionName: web
  hostnames:
    - "rancher.mydomain.com" # Replace with your domain
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rancher-httpsroute
  namespace: cattle-system
spec:
  parentRefs:
    - name: mydomain-istio-gw  # Replace with your gateway name
      namespace: default  # dont forget this
      sectionName: websecure
  hostnames:
    - "rancher.mydomain.com" # Replace with your domain
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: rancher  # Replace with your service name
          namespace: cattle-system
          port: 80
