apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kc-pg-statefulset
  namespace: keycloak
spec:
  serviceName: kc-pg-svc
  selector:
    matchLabels:
      app: kc-pg
  replicas: 1
  template:
    metadata:
      labels:
        app: kc-pg
    spec:
      containers:
        - name: postgresql-db
          image: postgres:15
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kc-pg-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-pg-secret
                  key: postgres-password
            - name: POSTGRES_DB
              value: keycloak
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
  # create a persistent volume claim for the database storage
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kc-pg-svc
  namespace: keycloak
spec:
  selector:
    app: kc-pg
  type: LoadBalancer
  loadBalancerIP: 192.168.5.38
  ports:
    - name: kc-pg
      port: 5432
      targetPort: 5432
