apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-group-rolebind
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubeAdmin  # This should match the group name in Keycloak
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io